services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'mysqld --default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - .:/app
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
